language: bash

sudo: false

env:
  global:
    - secure: 123123123123123123
    - GIT_NAME: Travis CI
    - GIT_EMAIL: builds@travis-ci.org
    - TRAVIS_REPO_SLUG: ChatScriptDeploy # Your repository
    - GIT_BRANCH: master
    - GH_TOKEN: 42Y42Y42Y42Y42Y # Your Github token
    - GIT_TAG: 'HelloBot-1.0-$TRAVIS_BUILD_NUMBER'

git:
  submodules: false

# safelist
branches:
  only:
  - master

before_install:
  - echo -e "machine github.com\n  login ci-user\n  password $GH_TOKEN" >> ~/.netrc

install: true

script: 
  - zip $GIT_TAG.zip -r BOTDATA/ files1.txt

after_success:
  - bash release/changefile.sh

before_deploy:
  - bash release/deploy.sh

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: 
    - "$GIT_TAG.zip"
  skip_cleanup: true
  on:
    repo: ChatScriptDeploy
    branch: $GIT_BRANCH
    tags: false